#!/bin/bash
echo "*** Getting the DIR "
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "DIR is '$DIR'"
# Generate gRPC code
python3 -m grpc_tools.protoc -I=./proto --python_out=. --grpc_python_out=. ./proto/image.proto
chmod +x "$DIR"/client
chmod +x "$DIR"/server
