#!/bin/bash
echo "*** Getting the DIR "
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "DIR is '$DIR'"
echo "*** Update Respositories and Install requirements"
apt-get update
apt-get install python3 -y
apt-get install python3-pip -y
python3 -m pip install -r "$DIR"/requirements.txt

